
/*
    This is a run once setup scrit to insert enumerated values into the database. It should be run once and then deleted to prevent duplicate entries in the database.
    It should be run only after the database has been created and the tables have been generated by the JPA entities. It should be run before any API calls are made to ensure that the necessary data is in place for the API to function correctly.
*/

insert into tblemployeestatuses (colstatusid,colstatus) values
(1,'Active');
insert into tblemployeestatuses (colstatusid,colstatus) values
(2,'Inactive');
insert into tblemployeestatuses (colstatusid,colstatus) values
(3,'Pending');    
insert into tblemployeestatuses (colstatusid,colstatus) values
(4,'Suspended');
insert into tblemployeestatuses (colstatusid,colstatus) values
(5,'Terminated');
insert into tblemployeestatuses (colstatusid,colstatus) values
(6,'On Leave');

insert into tblratetypes (colratetypeid,colratetype) values
(1,'Hourly');
insert into tblratetypes (colratetypeid,colratetype) values
(2,'Salaried');
insert into tblratetypes (colratetypeid,colratetype) values
(3,'Contract');
insert into tblratetypes (colratetypeid,colratetype) values
(4,'Commission');


insert into tblroles (colrolename) values                                 
('admin');

insert into tblroles (colrolename) values
('generalmanager'); -- documant and employee manager

insert into tblroles (colrolename) values
('documentmanager'); -- everything document

insert into tblroles (colrolename) values
('payrollmanager'); -- everythin employee


/*

    The following insert statement create aN admin login so that the api can be accessed

*/


--create master key to login to app
--password = xErxesi4@0r 
--uid = masterkey
insert into tblusers (
    colusername,  --username
    colstoredhash,  --storeHash == xErxesi4@0r
    colstoredsalt  --storedSalt
)
values('masterkey', 
'24846c0845b2a48c342506c55a62a2032e6bcb2b627b6987c38d9d11bf0229e0f96439dd7e5c2a3bc4d1f09649b9ca0e3095d16c34ca5b34431e49074a68aae8', 
'5fe5a8a71a4d1ead594cf1c07109fc03ea20e6b7d61c7bdf467da70690413e226a92babc04b22f95c4771ac6f566553dee9dad86ca46503346a5ef4c041cba156b257c67b4e483b558878afb022542b70190817283ac3382d15cab32da9b137c5df817cc51ba243dcc7f2609ba0fd2bfbeac3592ab432149caf35fc5239e5aa6'
);

--assign admin  with master key to admin role
insert into tblusersroles(coluser_id, colrole_id)
values(1,1);